xtd::servers::app::HttpServer
typedef HttpServer xtd::servers::app::HttpServer::http_app
typedef network::http::Server<network::utils::af_inet> xtd::servers::app::HttpServer::http_net
typedef boost::shared_ptr<servers::param::Handler> xtd::servers::app::HttpServer::t_param_handler
typedef counters::CounterManager::t_sptr xtd::servers::app::HttpServer::t_prober
typedef boost::shared_ptr<Action> xtd::servers::app::HttpServer::t_action
typedef map<string, t_action> xtd::servers::app::HttpServer::t_actions
typedef boost::shared_ptr<counters::Base> xtd::servers::app::HttpServer::t_counter
const uint32_t xtd::servers::app::HttpServer::mcs_defaultProbeDelay
const uint32_t xtd::servers::app::HttpServer::mcs_defaultTimeoutMs
const uint32_t xtd::servers::app::HttpServer::mcs_defaultThresholdMs
const char xtd::servers::app::HttpServer::mcs_defaultListenInterface[]
Referenced by parseConfig.
ConfParser::t_sptr xtd::servers::app::HttpServer::m_config
Referenced by parseConfig, getSnmpPath.
string xtd::servers::app::HttpServer::m_configPath
Referenced by HttpServer, parseConfig.
size_t xtd::servers::app::HttpServer::m_nbThread
Referenced by HttpServer, parseConfig, checkOptions, initialize, process.
size_t xtd::servers::app::HttpServer::m_timeoutMs
Referenced by HttpServer, checkOptions.
bool xtd::servers::app::HttpServer::m_isModeProbe
Referenced by modeProbeActivation, h_runAction.
bool xtd::servers::app::HttpServer::m_isDebug
Referenced by defineProbes.
string xtd::servers::app::HttpServer::m_snmpPath
Referenced by parseConfig, getSnmpPath.
uint32_t xtd::servers::app::HttpServer::m_probeDelay
Referenced by parseConfig, initialize.
t_prober xtd::servers::app::HttpServer::m_prober
Referenced by start, stop, addProbe, initialize, process, getSnmpPath.
counters::Value32::t_sptr xtd::servers::app::HttpServer::m_ramCounter
Referenced by defineProbes, initialize.
counters::AvgTimedValue::t_sptr xtd::servers::app::HttpServer::m_perfCounter
Referenced by defineProbes, initialize.
uint32_t xtd::servers::app::HttpServer::m_thresholdMs
Referenced by parseConfig, initialize.
string xtd::servers::app::HttpServer::m_httpHost
Referenced by parseConfig, process.
uint32_t xtd::servers::app::HttpServer::m_httpPort
Referenced by HttpServer, parseHttpPort, checkOptions, process.
network::utils::Config xtd::servers::app::HttpServer::m_httpConfig
Referenced by HttpServer, parseConfig, process.
string xtd::servers::app::HttpServer::m_httpConfigPath
Referenced by parseConfig, initialize, getSnmpPath.
t_param_handler xtd::servers::app::HttpServer::m_params
Referenced by start, initialize, getSnmpPath.
string xtd::servers::app::HttpServer::m_adminDir
Referenced by parseConfig, initialize.
t_actions xtd::servers::app::HttpServer::m_actions
Referenced by bind_action, h_runAction.
xtd::servers::app::HttpServer::HttpServer(bool p_isDebug=false)
References m_configPath, m_httpPort, m_nbThread, m_timeoutMs, m_httpConfig, handleUSR2, handleTERM.
xtd::servers::app::HttpServer::~HttpServer(void)
string xtd::servers::app::HttpServer::getCommonConfKey(void) const
Referenced by parseConfig, getSpecificConfKey.
string xtd::servers::app::HttpServer::getSpecificConfKey(void) const
References getCommonConfKey.
Referenced by parseConfig, parseHttpPort.
string xtd::servers::app::HttpServer::getSnmpPath(void) const
References m_snmpPath, m_httpConfigPath, m_prober, m_params, xtd::servers::param::JsonVisitor::writeExtraInfo, m_config.
Referenced by initialize.
void xtd::servers::app::HttpServer::handleTERM(void)
References stop.
Referenced by HttpServer.
int xtd::servers::app::HttpServer::process(void)
References defineProbes, m_httpHost, m_httpPort, m_httpConfig, m_nbThread, start, m_prober.
void xtd::servers::app::HttpServer::stop(void)
References m_prober.
Referenced by handleTERM.
void xtd::servers::app::HttpServer::start(void)
References m_params, m_prober.
Referenced by process.
void xtd::servers::app::HttpServer::parseConfig(void)
References getCommonConfKey, getSpecificConfKey, m_configPath, m_config, readConf, m_snmpPath, m_adminDir, m_probeDelay, m_httpConfigPath, m_httpHost, mcs_defaultListenInterface, m_nbThread, m_thresholdMs, parseHttpPort, m_httpConfig.
void xtd::servers::app::HttpServer::parseHttpPort(void)
References getSpecificConfKey, readConf, m_httpPort.
Referenced by parseConfig.
void xtd::servers::app::HttpServer::checkOptions(void)
References m_httpPort, m_nbThread, m_timeoutMs.
void xtd::servers::app::HttpServer::initialize(void)
References m_ramCounter, m_perfCounter, m_nbThread, m_thresholdMs, m_prober, m_probeDelay, getSnmpPath, m_params, m_adminDir, m_httpConfigPath.
status xtd::servers::app::HttpServer::defineProbes(void)
References m_isDebug, addProbe, m_ramCounter, m_perfCounter.
Referenced by process.
void xtd::servers::app::HttpServer::handleUSR2(void)
gestion vip hebex desactivation du service http et reponse 503 mode probe.
References modeProbeActivation.
Referenced by HttpServer.
void xtd::servers::app::HttpServer::modeProbeActivation(void)
References m_isModeProbe.
Referenced by handleUSR2.
void xtd::servers::app::HttpServer::setLastAdminLog(const string &p_message)
void xtd::servers::app::HttpServer::bind_action(const string &p_name, const string &p_description, h p_action)
References m_actions, h_runAction.
status xtd::servers::app::HttpServer::h_runAction(const string &p_name, h p_action, const uint32_t p_requestId, const network::http::Request &p_req, network::http::Response &p_res)
References m_actions, m_isModeProbe.
Referenced by bind_action.
status xtd::servers::app::HttpServer::addProbe(t_counter p_counter, const string &p_path)
References m_prober.
Referenced by defineProbes.
status xtd::servers::app::HttpServer::addProbe(const TType &p_value, const string &p_path, const string &p_name)
status xtd::servers::app::HttpServer::readConf(const std::string &p_key, T &p_dst, const T &p_default)
Referenced by parseConfig, parseHttpPort.
status xtd::servers::app::HttpServer::readConf(const std::string &p_key, T &p_dst)
void xtd::servers::app::HttpServer::process_mem_usage(uint32_t &p_vmUsage, uint32_t &p_residentSet)
process_mem_usage(double &, double &) - takes two doubles by reference, attempts to read the system-dependent data for a process' virtual memory size and resident set size, and return the results in KB.On failure, returns 0.0, 0.0
status xtd::servers::app::HttpServer::h_actionList(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
status xtd::servers::app::HttpServer::h_ident(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
recuperation des informations vmstatsrcupration de tous les compteurs et filtrage cration de la rponse http
status xtd::servers::app::HttpServer::h_index(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
status xtd::servers::app::HttpServer::h_counter(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
recuperation des informations vmstatsrcupration de tous les compteurs et filtrage cration de la rponse http
status xtd::servers::app::HttpServer::h_admin(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
status xtd::servers::app::HttpServer::h_conf(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
status xtd::servers::app::HttpServer::h_log(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)
status xtd::servers::app::HttpServer::h_probe(const uint32_t p_requestID, const network::http::Request &p_req, network::http::Response &p_res)