xtd::servers::app::HtmlOArchive
typedef boost::archive::xml_oarchive_impl<HtmlOArchive> xtd::servers::app::HtmlOArchive::base
typedef std::stack<context> xtd::servers::app::HtmlOArchive::t_info
typedef std::stack<Object*> xtd::servers::app::HtmlOArchive::t_objects
friend class boost::archive::detail::interface_oarchive< HtmlOArchive >
friend class boost::archive::basic_xml_oarchive< HtmlOArchive >
friend class boost::archive::save_access
t_info xtd::servers::app::HtmlOArchive::m_info
Referenced by save_start, save_end, save, save_override.
t_objects xtd::servers::app::HtmlOArchive::m_objects
Referenced by save_end.
bool xtd::servers::app::HtmlOArchive::m_pass
size_t xtd::servers::app::HtmlOArchive::m_depth
std::ostream& xtd::servers::app::HtmlOArchive::m_os
bool xtd::servers::app::HtmlOArchive::m_isVector
HtmlOArchive& xtd::servers::app::HtmlOArchive::operator*(T &p_value)
HtmlOArchive& xtd::servers::app::HtmlOArchive::operator/(T &p_value)
References save_binary, save_start, save_end, save_override, save, HtmlOArchive.
void xtd::servers::app::HtmlOArchive::save_binary(void *address, size_t count)
Referenced by operator/.
void xtd::servers::app::HtmlOArchive::save_start(const char *p_name)
References m_info.
Referenced by operator/.
void xtd::servers::app::HtmlOArchive::save_end(const char *p_name)
References m_info, m_objects.
Referenced by operator/.
void xtd::servers::app::HtmlOArchive::save_override(T &t, BOOST_PFTO int)
Referenced by operator/.
void xtd::servers::app::HtmlOArchive::save_override(const boost::serialization::nvp< T > &t, int)
void xtd::servers::app::HtmlOArchive::save_override(const boost::serialization::nvp< vector< T > > &t, int)
void xtd::servers::app::HtmlOArchive::save_override(const boost::serialization::nvp< std::deque< T > > &t, int)
void xtd::servers::app::HtmlOArchive::save_override(const boost::serialization::nvp< std::list< T > > &t, int)
void xtd::servers::app::HtmlOArchive::save(const char *)
References m_info.
Referenced by operator/.
void xtd::servers::app::HtmlOArchive::save(const string &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const unsigned char &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const unsigned short &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const unsigned int &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const unsigned long &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const unsigned long long &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const char &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const short &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const int &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const long &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const long long &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const bool &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const double &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const float &)
References m_info.
void xtd::servers::app::HtmlOArchive::save(const boost::serialization::collection_size_type &)
void xtd::servers::app::HtmlOArchive::save(const boost::serialization::item_version_type &)
References m_info.
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::object_id_type &t, int)
References m_info.
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::object_reference_type &, int)
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::version_type &t, int)
References m_info.
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::class_id_type &t, int)
References m_info.
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::class_id_reference_type &, int)
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::class_id_optional_type &t, int)
References m_info.
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::class_name_type &, int)
void xtd::servers::app::HtmlOArchive::save_override(const boost::archive::tracking_type &t, int)
References m_info.
xtd::servers::app::HtmlOArchive::HtmlOArchive(std::ostream &p_stream)
Referenced by operator/.