xtd::servers::param::Handler
typedef Base::t_sptr xtd::servers::param::Handler::t_param_sptr
typedef map<string, t_param_sptr> xtd::servers::param::Handler::t_params
string xtd::servers::param::Handler::m_actionPath
t_params xtd::servers::param::Handler::m_params
xtd::servers::param::Handler::Handler(const string &p_actionPath)
Constructor.
N/A p_actionPath the action path where to store persistent parameters (i.e. files containing values)
Handler::t_param_sptr xtd::servers::param::Handler::add(const string &p_name, const T &p_val, bool p_syncDisk=true)
Add a new parameter to the Handler.
N/A p_name the key name for the parameter p_val the the variable to register p_syncDisk the persistence parameter a shared ptr to the base param object
Referenced by bind.
Handler::t_param_sptr xtd::servers::param::Handler::bind(const string &p_name, T &p_val, bool p_syncDisk=true)
References add.
Handler::t_param_sptr xtd::servers::param::Handler::add(const string &p_name, t_param_sptr p_param, bool p_syncDisk=true)
Add a new parameter to the Handler.
N/A p_name the key name for the parameter p_param a shared ptr to an already existing parameter to register p_syncDisk the persistence parameter a shared ptr to the base param object
bool xtd::servers::param::Handler::exists(const string &p_name)
Existency checking.
N/A p_name the parameter to check true if already declared
References find.
void xtd::servers::param::Handler::initialize(void)
Initialization.
N/A
References find.
void xtd::servers::param::Handler::accept(Visitor &p_visitor) const
Add parameters to the Json visitor.
call accept on each parameter p_visitor the right visitor
bool xtd::servers::param::Handler::verify(const string &p_name, const string &p_src)
Function to verify if given string value can be setted on parameter.
p_name parameter value p_src the new value true if value can be setted N/A
References find.
bool xtd::servers::param::Handler::fromStr(const string &p_name, const string &p_src, const string &p_log)
Retreive parameter value from a string.
p_name the parameter name p_src the string value p_log logging message true if it succeeds N/A
References find.
Handler::t_params::iterator xtd::servers::param::Handler::find(const string &p_name)
return an iterator on a find call on map
make a find with lowercase on given name p_name the parameter name to find in map iterator result of map search
Referenced by initialize, exists, verify, fromStr, get, set, listen, constraint.
bool xtd::servers::param::Handler::get(const string &p_name, T &p_dst)
Get the current value of a parameter.
N/A p_name the parameter name p_dst the variable to store the content of the current value true if it succeeds
References find.
bool xtd::servers::param::Handler::set(const string &p_name, const T &p_src)
Set a parameter value.
N/A p_name the parameter name p_src the new value true if it succeeds
References find.
bool xtd::servers::param::Handler::listen(const string &p_name, T p_handler)
Specify the setter to modify the parameter.
N/A p_name the parameter name p_handler the modification handler true if it succeeds (i.e. parameter exists)
References find.
bool xtd::servers::param::Handler::constraint(const string &p_name, T p_handler)
Add a specific constraint to match while trying to modify a parameter.
Each time a modification is requested, the constraint will be checked Many constraints can be added, they will be checked in declaration order Opposite constraints must be avoided p_name the parameter name p_handler the specific constraint true if add succeeds
References find.
void xtd::servers::param::Handler::sync(const string &p_name)