xtd::logger
level
typedef map<string, level> xtd::logger::t_levels
string xtd::logger::m_name
bool xtd::logger::m_initialized
t_levels xtd::logger::m_levels
logger * xtd::logger::ms_pInstance
xtd::logger::logger(void)
Referenced by get.
void xtd::logger::initialize(void)
References crit.
Referenced by xtd::Application::execute.
void xtd::logger::initialize(const string &p_name, level p_level)
References setName, setLevel.
void xtd::logger::setLevel(const string &p_module, level p_level)
Referenced by initialize, clearAll, updateLevels, getLevel.
void xtd::logger::updateLevels(const string &p_regex, level p_level)
References setLevel.
void xtd::logger::setAllLevels(level p_level)
Referenced by xtd::Application::execute, setAllValueLevels.
void xtd::logger::setAllValueLevels(uint32_t p_level)
References setAllLevels, levelOf.
void xtd::logger::clearAll(level p_default)
References setLevel.
void xtd::logger::setName(const string &p_name)
Referenced by initialize.
logger::level xtd::logger::levelOf(const uint32_t &p_level)
References emerg, alert, crit, err, warning, notice, info, debug.
Referenced by setAllValueLevels.
uint32_t xtd::logger::valueOf(level p_level)
References emerg, alert, crit, err, warning, notice, info, debug.
string xtd::logger::stringOf(level p_level)
References emerg, alert, crit, err, warning, notice, info, debug.
logger::level xtd::logger::fromString(string p_level)
References emerg, alert, crit, err, warning, notice, info, debug.
logger::level xtd::logger::getLevel(const string &p_module)
References crit, setLevel.
logger::t_levels xtd::logger::getLevels(void)
bool xtd::logger::isValidStringLevel(string p_level)
logger & xtd::logger::get(void)
References logger.
Referenced by xtd::Application::execute.
static void xtd::logger::emerg(const string &p_module, const string &p_format, Args...p_args)
static void xtd::logger::alert(const string &p_module, const string &p_format, Args...p_args)
static void xtd::logger::crit(const string &p_module, const string &p_format, Args...p_args)
Referenced by xtd::Application::execute, xtd::ConfParser::ConfParser, xtd::error::do_throw.
static void xtd::logger::err(const string &p_module, const string &p_format, Args...p_args)
Referenced by xtd::ConfParser::ConfParser.
static void xtd::logger::warning(const string &p_module, const string &p_format, Args...p_args)
static void xtd::logger::info(const string &p_module, const string &p_format, Args...p_args)
Referenced by xtd::ConfParser::get.
static void xtd::logger::notice(const string &p_module, const string &p_format, Args...p_args)
static void xtd::logger::debug(const string &p_module, const string &p_format, Args...p_args)
Referenced by xtd::ConfParser::ConfParser.
static string xtd::logger::format_vargs(string const &p_fmt, Arguments &&...p_args)
Referenced by xtd::error::do_throw.
void xtd::logger::wrap_syslog(int __pri, const char *__fmt,...)
void xtd::logger::log(level p_level, const string &p_module, const string &p_format, Args...p_args)