xtd::ConfParser
typedef map<string, string> xtd::ConfParser::t_value_map
typedef std::pair<string, string> xtd::ConfParser::t_section_data
typedef vector<t_section_data > xtd::ConfParser::t_section_list
typedef map<string, string> xtd::ConfParser::t_param_map
typedef boost::shared_ptr<ConfParser> xtd::ConfParser::t_sptr
t_value_map xtd::ConfParser::m_values
Referenced by ConfParser, get, exists, dumpKeys, getParamMap, getValueMap.
t_section_list xtd::ConfParser::m_sections
Referenced by ConfParser, find, begin, end.
int xtd::ConfParser::m_nblines
Referenced by ConfParser.
string xtd::ConfParser::m_filename
Referenced by ConfParser, get, getFilePath.
t_param_map xtd::ConfParser::m_paramMap
Referenced by ConfParser.
xtd::ConfParser::ConfParser(const string &p_path)
References xtd::ok, xtd::error::do_throw, HERE.
xtd::ConfParser::ConfParser(const string &p_path, const t_param_map &p_params)
References xtd::ok, xtd::error::do_throw, HERE, xtd::logger::debug, m_filename, xtd::logger::crit, xtd::error, xtd::logger::err, m_paramMap, m_nblines, m_values, m_sections.
const string & xtd::ConfParser::getFilePath(void) const
References m_filename.
ConfParser::const_iterator xtd::ConfParser::find(const char *p_name) const
ConfParser::const_iterator xtd::ConfParser::find(const string &p_key) const
References m_sections.
ConfParser::const_iterator xtd::ConfParser::end(void) const
References xtd::ConfParser::const_iterator::const_iterator, m_sections.
ConfParser::const_iterator xtd::ConfParser::begin(void) const
References xtd::ConfParser::const_iterator::const_iterator, m_sections.
status xtd::ConfParser::get(const string &p_name, string &p_dval) const
References m_values, xtd::logger::info, m_filename, HERE, xtd::error, xtd::ok.
status xtd::ConfParser::get(const string &p_name, const char *&p_dval) const
References m_values, xtd::logger::info, m_filename, HERE, xtd::error, xtd::ok.
status xtd::ConfParser::get(const string &p_name, char &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, unsigned char &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, unsigned short &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, int &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, long &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, unsigned long long &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, unsigned long &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, unsigned int &p_ival) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, double &p_dval) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, float &p_dval) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get(const string &p_name, bool &p_dval) const
References xtd::ok, xtd::error.
status xtd::ConfParser::get_default(const string &p_key, T &p_dest, const T &p_default)
References xtd::ok, xtd::notfound, exists, dumpKeys, getParamMap, getValueMap.
bool xtd::ConfParser::exists(const string &p_name) const
Indique si la clef p_name existe dans le fichier de conf.
p_name clef à chercher vrai si p_name existe, faux sinon
References m_values.
Referenced by get_default.
void xtd::ConfParser::dumpKeys(std::ostream &p_stream) const
dump all keys found in conf file p_stream output stream
References m_values.
Referenced by get_default.
const ConfParser::t_param_map & xtd::ConfParser::getParamMap(void) const
References m_values.
Referenced by get_default.
const ConfParser::t_value_map & xtd::ConfParser::getValueMap(void) const
References m_values.
Referenced by get_default.
status xtd::ConfParser::initialize(const string &p_fileName)
status xtd::ConfParser::parseSection(char *p_line, int &p_readOffset, char p_prefix[255])
status xtd::ConfParser::parseFile(char *p_line)
status xtd::ConfParser::loadFile(const string &p_filename)
status xtd::ConfParser::evaluateVal(const string &p_keyName, char *p_pLine, char *p_dest, std::size_t p_maxChar)