boost::property_tree::json_parser
void boost::property_tree::json_parser::read_json(std::basic_istream< typename Ptree::key_type::value_type > &stream, Ptree &pt)
Read JSON from a the given stream and translate it to a property tree. Clears existing contents of property tree. In case of error the property tree unmodified. Items of JSON arrays are translated into ptree keys with empty names. Members of objects are translated into named keys. JSON data can be a string, a numeric value, or one of literals "null", "true" and "false". During parse, any of the above is copied verbatim into ptree data string. json_parser_error In case of error deserializing the property tree. stream Stream from which to read in the property tree. pt The property tree to populate.
Referenced by write_json.
void boost::property_tree::json_parser::read_json(const std::string &filename, Ptree &pt, const std::locale &loc=std::locale())
Read JSON from a the given file and translate it to a property tree. Clears existing contents of property tree. In case of error the property tree unmodified. Items of JSON arrays are translated into ptree keys with empty names. Members of objects are translated into named keys. JSON data can be a string, a numeric value, or one of literals "null", "true" and "false". During parse, any of the above is copied verbatim into ptree data string. json_parser_error In case of error deserializing the property tree. filename Name of file from which to read in the property tree. pt The property tree to populate. loc The locale to use when reading in the file contents.
void boost::property_tree::json_parser::write_json(std::basic_ostream< typename Ptree::key_type::value_type > &stream, const Ptree &pt, bool pretty=true)
Translates the property tree to JSON and writes it the given output stream. Any property tree key containing only unnamed subkeys will be rendered as JSON arrays. pt cannot contain keys that have both subkeys and non-empty data. json_parser_error In case of error translating the property tree to JSON or writing to the output stream. stream The stream to which to write the JSON representation of the property tree. pt The property tree to tranlsate to JSON and output. pretty Whether to pretty-print. Defaults to true for backward compatibility.
References write_json_internal.
Referenced by write_json.
void boost::property_tree::json_parser::write_json(const std::string &filename, const Ptree &pt, const std::locale &loc=std::locale(), bool pretty=true)
Translates the property tree to JSON and writes it the given file. Any property tree key containing only unnamed subkeys will be rendered as JSON arrays. pt cannot contain keys that have both subkeys and non-empty data. json_parser_error In case of error translating the property tree to JSON or writing to the file. filename The name of the file to which to write the JSON representation of the property tree. pt The property tree to translate to JSON and output. loc The locale to use when writing out to the output file. pretty Whether to pretty-print. Defaults to true and last place for backward compatibility.
References write_json_internal, read_json, write_json.
std::basic_string<Ch> boost::property_tree::json_parser::create_escapes(const std::basic_string< Ch > &s)
Referenced by write_json_helper.
void boost::property_tree::json_parser::write_json_helper(std::basic_ostream< typename Ptree::key_type::value_type > &stream, const Ptree &pt, int indent, bool pretty)
References create_escapes.
Referenced by write_json_internal.
bool boost::property_tree::json_parser::verify_json(const Ptree &pt, int depth)
Referenced by write_json_internal.
void boost::property_tree::json_parser::write_json_internal(std::basic_ostream< typename Ptree::key_type::value_type > &stream, const Ptree &pt, const std::string &filename, bool pretty)
References verify_json, write_json_helper.
Referenced by write_json.