xtd::counters::Base
typedef boost::shared_ptr<Base> xtd::counters::Base::t_sptr
typedef map<string, string> xtd::counters::Base::t_data
friend class Composed
string xtd::counters::Base::m_name
Referenced by getName, xtd::counters::Composed::addItem.
boost::mutex xtd::counters::Base::m_mutex
Referenced by xtd::counters::AvgTimedValue::stopChrono, xtd::counters::AvgTimedValue::addResponseTime, visit, update, xtd::counters::InstantFreq::tick.
xtd::counters::Base::Base(const string &p_name)
xtd::counters::Base::~Base(void)
void xtd::counters::Base::visit(Visitor &p_visitor) const
References m_mutex, visit_safe.
Referenced by xtd::counters::Composed::visit_safe.
void xtd::counters::Base::update(void)
References m_mutex, update_safe.
Referenced by xtd::counters::Composed::update_safe.
const string & xtd::counters::Base::getName(void) const
References m_name.
void xtd::counters::Base::update_safe(void)
Referenced by update.
virtual void xtd::counters::Base::visit_safe(Visitor &p_visitor) const =0
Referenced by visit.