xtd::counters::Value
typedef boost::shared_ptr<Value<TType> > xtd::counters::Value< TType >::t_sptr
friend class Composed
bool xtd::counters::Value< TType >::m_isNaN
TType xtd::counters::Value< TType >::m_value
Atomic xtd::counters::Value< TType >::m_atom
xtd::counters::Value< TType >::Value(const string &p_name)
virtual xtd::counters::Value< TType >::~Value(void)
Value& xtd::counters::Value< TType >::NaN(void)
Referenced by xtd::counters::AvgTimedValue::AvgTimedValue, xtd::counters::AvgTimedValue::update_safe.
bool xtd::counters::Value< TType >::isNaN(void) const
Value& xtd::counters::Value< TType >::operator=(const TType &p_value)
Referenced by xtd::counters::Freq::operator=, xtd::counters::InstantFreq::operator=.
Value& xtd::counters::Value< TType >::operator++(void)
Value& xtd::counters::Value< TType >::operator++(int)
Value& xtd::counters::Value< TType >::operator--(void)
Value& xtd::counters::Value< TType >::operator--(int)
const TType& xtd::counters::Value< TType >::getValue(void) const
void xtd::counters::Value< TType >::visit_safe(Visitor &p_visitor) const