xtd::counters::Composed
vector<Base*> xtd::counters::Composed::m_items
xtd::counters::Composed::Composed(const string &p_name)
virtual xtd::counters::Composed::~Composed(void)
References addItem, update_safe, visit_safe.
void xtd::counters::Composed::addItem(Base &p_item)
References xtd::counters::Base::m_name.
Referenced by xtd::counters::AvgTimedValue::AvgTimedValue, xtd::counters::Cache::Cache, ~Composed, xtd::counters::Perf::Perf.
void xtd::counters::Composed::update_safe(void)
References xtd::counters::Base::update.
Referenced by ~Composed.
void xtd::counters::Composed::visit_safe(Visitor &p_visitor) const
References xtd::counters::Base::visit.
Referenced by ~Composed.