xtd::counters::AvgTimedValue
typedef std::pair<boost::posix_time::ptime, uint32_t> xtd::counters::AvgTimedValue::t_elem
typedef std::deque<t_elem> xtd::counters::AvgTimedValue::t_samples
typedef std::deque< boost::posix_time::ptime > xtd::counters::AvgTimedValue::t_timevect
typedef boost::shared_ptr<AvgTimedValue> xtd::counters::AvgTimedValue::t_sptr
friend class Composed
t_samples xtd::counters::AvgTimedValue::m_samples
Referenced by addResponseTime, update_safe.
t_timevect xtd::counters::AvgTimedValue::m_startTimes
Referenced by startChrono, stopChrono.
vector<uint32_t> xtd::counters::AvgTimedValue::m_reseted
Referenced by startChrono, stopChrono.
Freq xtd::counters::AvgTimedValue::m_globalPerf
Referenced by AvgTimedValue, addResponseTime.
InstantFreq xtd::counters::AvgTimedValue::m_instantPerf
Referenced by AvgTimedValue, addResponseTime.
Value32 xtd::counters::AvgTimedValue::m_mean
Referenced by AvgTimedValue, update_safe.
Value32 xtd::counters::AvgTimedValue::m_min
Referenced by AvgTimedValue, update_safe.
Value32 xtd::counters::AvgTimedValue::m_max
Referenced by AvgTimedValue, update_safe.
Value32 xtd::counters::AvgTimedValue::m_overThreshold
Referenced by AvgTimedValue, addResponseTime.
const uint32_t xtd::counters::AvgTimedValue::m_timeDeltaMs
Referenced by addResponseTime.
const uint32_t xtd::counters::AvgTimedValue::m_thresholdMs
Referenced by addResponseTime.
bool xtd::counters::AvgTimedValue::m_assert
Referenced by addResponseTime, setAssert.
xtd::counters::AvgTimedValue::AvgTimedValue(const string &p_name, uint32_t p_nbThread, uint32_t p_timeDeltaMs=5 *60 *1000, uint32_t p_thresholdMs=0)
References xtd::counters::Composed::addItem, m_globalPerf, m_instantPerf, m_mean, m_min, m_max, m_overThreshold, xtd::counters::Value< TType >::NaN.
virtual xtd::counters::AvgTimedValue::~AvgTimedValue(void)
References startChrono, stopChrono, addResponseTime, setAssert, update_safe.
void xtd::counters::AvgTimedValue::startChrono(uint32_t p_requestID)
References m_reseted, m_startTimes.
Referenced by ~AvgTimedValue.
void xtd::counters::AvgTimedValue::stopChrono(uint32_t p_requestID)
References xtd::counters::Base::m_mutex, m_reseted, m_startTimes.
Referenced by ~AvgTimedValue.
void xtd::counters::AvgTimedValue::addResponseTime(uint32_t p_timeUs)
References xtd::counters::Base::m_mutex, m_globalPerf, xtd::counters::Freq::tick, m_instantPerf, xtd::counters::InstantFreq::tick, m_samples, m_thresholdMs, m_overThreshold, m_assert, m_timeDeltaMs.
Referenced by ~AvgTimedValue.
void xtd::counters::AvgTimedValue::setAssert(const bool p_assert)
References m_assert.
Referenced by ~AvgTimedValue.
void xtd::counters::AvgTimedValue::update_safe(void)
References m_samples, m_min, xtd::counters::Value< TType >::NaN, m_max, m_mean.
Referenced by ~AvgTimedValue.
bool xtd::counters::AvgTimedValue::is_greater(t_elem &p_elem, const boost::posix_time::ptime &p_maxTime)
void xtd::counters::AvgTimedValue::shrink_safe(void)
On calcul le timestamp "frontiere" entre les elements qu'il faut garder et ceux qu'il faut supprimerOn trouve (en dichotomie) le premier element a supprimerOn supprime les echantillons a partir de cet element jusqu'a la fin
void xtd::counters::AvgTimedValue::compute_safe(void)
bool xtd::counters::AvgTimedValue::thresdhold_safe(uint32_t p_timeUs)
void xtd::counters::AvgTimedValue::responsetime_safe(uint32_t p_timeUs)