xtd::network::http::Response
typedef map<string, string> xtd::network::http::Response::t_header_map
string xtd::network::http::Response::m_version
code xtd::network::http::Response::m_status
t_header_map xtd::network::http::Response::m_headers
string xtd::network::http::Response::m_data
bool xtd::network::http::Response::m_cachable
xtd::network::http::Response::Response(void)
References xtd::network::http::bad_request.
void xtd::network::http::Response::setStatus(code p_status)
void xtd::network::http::Response::addHeader(const string &p_name, const string &p_value)
Referenced by finalize.
void xtd::network::http::Response::setData(const string &p_data)
void xtd::network::http::Response::appendData(const string &p_data)
void xtd::network::http::Response::setVersion(const string &p_version)
void xtd::network::http::Response::setCachable(bool p_status)
code xtd::network::http::Response::getStatus(void) const
Referenced by write.
bool xtd::network::http::Response::getHeader(const string &p_name, string &p_value) const
const Response::t_header_map & xtd::network::http::Response::getHeaders(void) const
Referenced by write.
const string & xtd::network::http::Response::getData(void) const
Referenced by finalize, write.
const string & xtd::network::http::Response::getVersion(void) const
Referenced by write.
void xtd::network::http::Response::write(std::ostream &p_response) const
References statusToMessage, getStatus, getData, getVersion, getHeaders.
void xtd::network::http::Response::finalize(void)
References addHeader, getData.
string xtd::network::http::Response::statusToMessage(code p_status)
References xtd::network::http::proceeed, xtd::network::http::switch_protocol, xtd::network::http::ok, xtd::network::http::created, xtd::network::http::accepted, xtd::network::http::no_content, xtd::network::http::partial_content, xtd::network::http::multiple_choices, xtd::network::http::moved_permanently, xtd::network::http::moved_temporarily, xtd::network::http::not_modified, xtd::network::http::bad_request, xtd::network::http::unauthorized, xtd::network::http::forbidden, xtd::network::http::not_found, xtd::network::http::method_not_allowed, xtd::network::http::internal_error, xtd::network::http::not_implemented, xtd::network::http::bad_gateway, xtd::network::http::service_unavailable.
Referenced by write.