xtd::network::http::HtmlTemplate
const string xtd::network::http::HtmlTemplate::mcs_htmlTemplate
string xtd::network::http::HtmlTemplate::m_title
vector<string> xtd::network::http::HtmlTemplate::m_cssList
vector<string> xtd::network::http::HtmlTemplate::m_jsList
string xtd::network::http::HtmlTemplate::m_metaDescription
string xtd::network::http::HtmlTemplate::m_metaKeywords
string xtd::network::http::HtmlTemplate::m_mimeType
string xtd::network::http::HtmlTemplate::m_charset
string xtd::network::http::HtmlTemplate::m_favico
xtd::network::http::HtmlTemplate::HtmlTemplate(bool p_defaultAssests=false)
References setFavico, addJs, addCss.
HtmlTemplate & xtd::network::http::HtmlTemplate::setFavico(const string &p_ico)
Referenced by HtmlTemplate.
HtmlTemplate& xtd::network::http::HtmlTemplate::setTitle(const string &p_title)
HtmlTemplate& xtd::network::http::HtmlTemplate::addCss(const string &p_cssUrl)
Referenced by HtmlTemplate.
HtmlTemplate& xtd::network::http::HtmlTemplate::addJs(const string &p_jsUrl)
Referenced by HtmlTemplate.
HtmlTemplate& xtd::network::http::HtmlTemplate::setMetaKeywords(const string &p_keywords)
HtmlTemplate& xtd::network::http::HtmlTemplate::setCharset(const string &p_charset)
HtmlTemplate& xtd::network::http::HtmlTemplate::setMetaDescription(const string &p_description)
HtmlTemplate& xtd::network::http::HtmlTemplate::setContentType(const string &p_mimeType, const string &p_charset)
status xtd::network::http::HtmlTemplate::resolve(string &p_result)
References xtd::network::http::ok, xtd::network::http::Template::resolve, xtd::network::http::Template::val, xtd::network::http::Template::setTemplate, xtd::network::http::Template::setData.