xtd::network::utils::Config
bool xtd::network::utils::Config::m_noDelay
bool xtd::network::utils::Config::m_reuseAddr
bool xtd::network::utils::Config::m_linger
uint32_t xtd::network::utils::Config::m_lingerTime
bool xtd::network::utils::Config::m_compress
codec xtd::network::utils::Config::m_compressionCodec
uint32_t xtd::network::utils::Config::m_dnsCacheTTL
uint32_t xtd::network::utils::Config::m_connectTimeoutMs
uint32_t xtd::network::utils::Config::m_sendTimeoutMs
uint32_t xtd::network::utils::Config::m_receiveTimeoutMs
xtd::network::utils::Config::Config(void)
default constructor set nothing
References xtd::network::utils::zlib.
xtd::network::utils::Config::Config(uint32_t p_flags, uint32_t p_lingerInterval=0)
Constructor make the socket setting.
p_flags configuration flags p_lingerInterval linger interval
References setNoDelay, xtd::network::utils::nodelay, setReuseAddr, xtd::network::utils::reuseaddr, setLinger, xtd::network::utils::linger, setCompress, xtd::network::utils::compress.
bool xtd::network::utils::Config::getLinger(void) const
uint32_t xtd::network::utils::Config::getLingerTime(void) const
bool xtd::network::utils::Config::getNoDelay(void) const
bool xtd::network::utils::Config::getReuseAddr(void) const
bool xtd::network::utils::Config::getCompress(void) const
codec xtd::network::utils::Config::getCompressionCodec(void) const
uint32_t xtd::network::utils::Config::getConnectTimeoutMs(void) const
uint32_t xtd::network::utils::Config::getSendTimeoutMs(void) const
uint32_t xtd::network::utils::Config::getReceiveTimeoutMs(void) const
uint32_t xtd::network::utils::Config::getDnsCacheTTL(void) const
void xtd::network::utils::Config::setLinger(bool p_linger, uint32_t p_lingerTime)
Referenced by Config.
void xtd::network::utils::Config::setNoDelay(bool p_noDelay)
Referenced by Config.
void xtd::network::utils::Config::setReuseAddr(bool p_reuseAddr)
Referenced by Config.
void xtd::network::utils::Config::setCompress(bool p_compress)
Referenced by Config.
void xtd::network::utils::Config::setCompressionCodec(codec p_compressionCodec)
void xtd::network::utils::Config::setConnectTimeoutMs(uint32_t p_ms)
void xtd::network::utils::Config::setSendTimeoutMs(uint32_t p_ms)
void xtd::network::utils::Config::setReceiveTimeoutMs(uint32_t p_ms)
void xtd::network::utils::Config::setDnsCacheTTL(uint32_t p_ms)