xtd::network::http::Template
typedef cpptempl::data_map xtd::network::http::Template::t_map
typedef cpptempl::data_list xtd::network::http::Template::t_list
typedef cpptempl::data_ptr xtd::network::http::Template::t_val
string xtd::network::http::Template::m_template
cpptempl::data_map xtd::network::http::Template::m_data
string xtd::network::http::Template::m_content
static t_val xtd::network::http::Template::val(T p_val)
Referenced by add, xtd::network::http::HtmlTemplate::resolve, xtd::network::http::XmlTemplate::resolve.
Template::t_val xtd::network::http::Template::val(const string &p_val, bool p_encode=false)
References xtd::network::http::cpptempl::make_data.
xtd::network::http::Template::Template(const string &p_contentType=mcs_defaultContentType)
xtd::network::http::Template::~Template(void)
Template& xtd::network::http::Template::setTemplate(const string &p_text)
Referenced by loadTemplate, xtd::network::http::HtmlTemplate::resolve, xtd::network::http::XmlTemplate::resolve.
Template& xtd::network::http::Template::setData(cpptempl::data_map &p_data)
Referenced by xtd::network::http::HtmlTemplate::resolve, xtd::network::http::XmlTemplate::resolve.
Template& xtd::network::http::Template::setContent(const string &p_text)
status xtd::network::http::Template::resolve(string &p_result)
References xtd::network::http::Generator::addError, xtd::network::http::cpptempl::parse, xtd::network::http::cpptempl::TemplateException::what, xtd::network::http::ok.
Referenced by xtd::network::http::HtmlTemplate::resolve, xtd::network::http::XmlTemplate::resolve.
status xtd::network::http::Template::loadTemplate(const string &p_path)
References setTemplate, xtd::network::http::ok.
Template& xtd::network::http::Template::add(const string &p_key, T p_val)
Template & xtd::network::http::Template::add(const string &p_key, const string &p_val, bool p_encode)
References val.