xtd::network::http::Request
t_method
t_version
typedef std::multimap<string, string> xtd::network::http::Request::t_param_map
typedef map<string, string> xtd::network::http::Request::t_header_map
string xtd::network::http::Request::m_rawUrl
t_method xtd::network::http::Request::m_method
string xtd::network::http::Request::m_path
t_param_map xtd::network::http::Request::m_cgi
t_param_map xtd::network::http::Request::m_post
t_header_map xtd::network::http::Request::m_headers
string xtd::network::http::Request::m_versionStr
t_version xtd::network::http::Request::m_version
bool xtd::network::http::Request::m_cgiToLower
boost::regex xtd::network::http::Request::m_regex_tooManyStartingSlash
boost::regex xtd::network::http::Request::m_regex_tooManyEndingSlash
std::ostream& operator<<(std::ostream &, const Request &)
xtd::network::http::Request::Request(bool p_cgiToLower=true)
void xtd::network::http::Request::setMethod(t_method p_method)
Referenced by readHead.
void xtd::network::http::Request::addCgi(const string &p_key, const string &p_value)
Referenced by xtd::network::http::hex_to_string::operator().
void xtd::network::http::Request::addPost(const string &p_key, const string &p_value)
Referenced by getDataSize.
void xtd::network::http::Request::addHeader(const string &p_name, const string &p_value)
Referenced by getRawUrl.
void xtd::network::http::Request::setVersion(const string &p_version)
Referenced by getRawUrl.
void xtd::network::http::Request::setVersion(t_version p_version)
void xtd::network::http::Request::removeCgi(const string &p_key)
Referenced by removeData.
void xtd::network::http::Request::removePost(const string &p_key)
Referenced by removeData.
void xtd::network::http::Request::removeData(const string &p_key)
References removeCgi, removePost.
status xtd::network::http::Request::readQS(const string &p_qs)
status xtd::network::http::Request::readHead(std::istream &p_request)
References xtd::network::http::ok, setMethod, METHOD_GET, METHOD_POST, METHOD_HEAD.
Referenced by read.
status xtd::network::http::Request::read(std::istream &p_request)
References xtd::network::http::ok, readHead.
Request::t_method xtd::network::http::Request::getMethod(void) const
Referenced by xtd::network::http::operator<<.
const string & xtd::network::http::Request::getPath(void) const
Referenced by xtd::network::http::operator<<.
string xtd::network::http::Request::getQS(void) const
string xtd::network::http::Request::getRawUrl(void) const
References setVersion, VERSION_1_0, VERSION_1_1, xtd::network::http::ok, addHeader.
const Request::t_param_map & xtd::network::http::Request::getCgis(void) const
Referenced by xtd::network::http::operator<<.
const Request::t_param_map & xtd::network::http::Request::getPosts(void) const
Referenced by xtd::network::http::operator<<.
Request::t_param_map xtd::network::http::Request::getParams(void) const
bool xtd::network::http::Request::existsCgi(const string &p_key) const
bool xtd::network::http::Request::existsPost(const string &p_key) const
bool xtd::network::http::Request::existsParam(const string &p_key) const
bool xtd::network::http::Request::existsHeader(const string &p_name) const
bool xtd::network::http::Request::getHeader(const string &p_name, string &p_value) const
Referenced by getDataSize.
const Request::t_header_map & xtd::network::http::Request::getHeaders(void) const
Referenced by xtd::network::http::operator<<.
const string & xtd::network::http::Request::getVersionStr(void) const
Referenced by xtd::network::http::operator<<.
Request::t_version xtd::network::http::Request::getVersion(void) const
status xtd::network::http::Request::getDataSize(size_t &p_length) const
References getHeader, xtd::network::http::ok, addPost.
bool xtd::network::http::Request::getCgi(const string &p_key, T &p_dst) const
void xtd::network::http::Request::getCgi(const string &p_key, vector< T > &p_dst) const
void xtd::network::http::Request::getCgi(const string &p_key, T &p_dst, const T &p_default) const
bool xtd::network::http::Request::getPost(const string &p_key, T &p_dst) const
void xtd::network::http::Request::getPost(const string &p_key, vector< T > &p_dst) const
void xtd::network::http::Request::getPost(const string &p_key, T &p_dst, const T &p_default) const
bool xtd::network::http::Request::getParam(const string &p_key, T &p_dst) const
void xtd::network::http::Request::getParam(const string &p_key, vector< T > &p_dst) const
void xtd::network::http::Request::getParam(const string &p_key, T &p_dst, const T &p_default) const
void xtd::network::http::Request::getParam(const string &p_key, vector< T > &p_dst, const vector< T > &p_default) const
status xtd::network::http::Request::readData(std::istream &p_request)
on lit jusqu'a eof et on append dans m_data chaque chunk
status xtd::network::http::Request::readDataFormEncoded(const string &p_data)
status xtd::network::http::Request::readHeaders(std::istream &p_request)
status xtd::network::http::Request::readVersion(const string &p_version)
status xtd::network::http::Request::readUrl(const string &p_url)
status xtd::network::http::Request::readMethod(const string &p_method)
status xtd::network::http::Request::readInitial(std::istream &p_request)
string xtd::network::http::Request::paramValueDecode(const string &p_value)
void xtd::network::http::Request::normalizePath(const string &p_path)
on effecture une etape de nornmalisation de la ressource demandee
bool xtd::network::http::Request::as(const string &p_src, string &p_dst) const
bool xtd::network::http::Request::as(const string &p_src, bool &p_dst) const
bool xtd::network::http::Request::as(const string &p_src, uint8_t &p_dst) const
bool xtd::network::http::Request::as(const string &p_src, TDst &p_dst) const
bool xtd::network::http::Request::existsData(const t_param_map &p_src, const string &p_key) const
bool xtd::network::http::Request::getData(const t_param_map &p_src, const string &p_key, T &p_dst) const
void xtd::network::http::Request::getData(const t_param_map &p_src, const string &p_key, vector< T > &p_dst) const
void xtd::network::http::Request::getData(const t_param_map &p_src, const string &p_key, T &p_dst, const T &p_default) const
void xtd::network::http::Request::getData(const t_param_map &p_src, const string &p_key, vector< T > &p_dst, const vector< T > &p_default) const