xtd::network::bip::Client
cnxstatus
pret à envoyer une nouvelle requête (nouveau send)
typedef base::Client<TDomain> xtd::network::bip::Client< TRequest, TResponse, TDomain >::TBase
typedef TBase::cnx_sptr_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::cnx_sptr_t
typedef TRequest xtd::network::bip::Client< TRequest, TResponse, TDomain >::TReq
typedef TResponse xtd::network::bip::Client< TRequest, TResponse, TDomain >::TRes
boost::interprocess::interprocess_semaphore xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_userSemaphore
Semaphore uitilise pour bloquer l'utilisateur soit dans le send (noget) soit dans le receive
cnxstatus xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_status
utils::vectorBytes_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_response
boost::posix_time::ptime xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_lastSend
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_sendTotal
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_sendError
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_sendSuccess
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_sendTimeout
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_receiveTotal
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_receiveError
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_receiveTimeout
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_receiveSuccess
uint32_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::m_lastRTTMs
xtd::network::bip::Client< TRequest, TResponse, TDomain >::Client(const utils::Config &p_conf)
virtual xtd::network::bip::Client< TRequest, TResponse, TDomain >::~Client(void)
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getSendTotal(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getSendSuccess(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getSendTimeout(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getSendError(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getReceiveTotal(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getReceiveSuccess(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getReceiveTimeout(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getReceiveError(void) const
const uint32_t& xtd::network::bip::Client< TRequest, TResponse, TDomain >::getLastRTTMs(void) const
References xtd::network::bip::Client< TRequest, TResponse, TDomain >::send, xtd::network::bip::Client< TRequest, TResponse, TDomain >::receive, xtd::network::bip::Client< TRequest, TResponse, TDomain >::shouldReceive.
status xtd::network::bip::Client< TRequest, TResponse, TDomain >::send(const TRequest &p_request, bool p_debug)
envoi d'une structure requête au server
p_request la requête p_debug si vrai, envoyer aussi la partie débug de la structure status::ok si tout va bien, status::error sinon Non bloquant, status::ok ne veut pas dire que le message est bien arrivé, simplement que l'objet étaient en étant d'envoyer une requête (pas déjà en attente de réponse par exemple).
Referenced by xtd::network::bip::Client< TRequest, TResponse, TDomain >::getLastRTTMs.
status xtd::network::bip::Client< TRequest, TResponse, TDomain >::receive(TResponse &p_response, bool &p_debug)
reception de la structure réponse
p_response structure à remplir avec la réponse du server p_debug sortira à la valeur true si le serveur a envoyé la partie débug de la structure status::ok si tout va bien, status::timeout en cas de timeout et staus::error en cas d'erreur. Cette méthode est bloquante, elle attend la réception effective de la réponse du serveur ou la survenue d'une erreur/timeout.
Referenced by xtd::network::bip::Client< TRequest, TResponse, TDomain >::getLastRTTMs.
virtual bool xtd::network::bip::Client< TRequest, TResponse, TDomain >::shouldReceive(const TRequest &p_request, const bool p_requestDebug)
Referenced by xtd::network::bip::Client< TRequest, TResponse, TDomain >::getLastRTTMs.
cnx_sptr_t xtd::network::bip::Client< TRequest, TResponse, TDomain >::createCnx(string p_hostname, uint32_t p_port)
void xtd::network::bip::Client< TRequest, TResponse, TDomain >::do_receive(void)
void xtd::network::bip::Client< TRequest, TResponse, TDomain >::onSent(const boost::system::error_code p_error, bool p_shouldReceive)
void xtd::network::bip::Client< TRequest, TResponse, TDomain >::onReceived(const boost::system::error_code p_error, utils::sharedBuf_t p_response)