xtd::network::http::cpptempl
TokenType
typedef boost::shared_ptr<Data> xtd::network::http::cpptempl::data_ptr
typedef vector<data_ptr> xtd::network::http::cpptempl::data_list
typedef map<string, data_ptr> xtd::network::http::cpptempl::data_map
typedef boost::shared_ptr<Token> xtd::network::http::cpptempl::token_ptr
typedef vector<token_ptr> xtd::network::http::cpptempl::token_vector
data_ptr xtd::network::http::cpptempl::parse_val(string key, data_map &data)
References make_data.
Referenced by xtd::network::http::cpptempl::TokenVar::gettext, xtd::network::http::cpptempl::TokenFor::gettext, xtd::network::http::cpptempl::TokenIf::is_true, make_data.
void xtd::network::http::cpptempl::parse_tree(token_vector &tokens, token_vector &tree, TokenType until)
References TOKEN_TYPE_FOR, TOKEN_TYPE_ENDFOR, TOKEN_TYPE_IF, TOKEN_TYPE_ENDIF.
Referenced by parse, xtd::network::http::cpptempl::TokenEnd::TokenEnd.
token_vector & xtd::network::http::cpptempl::tokenize(string text, token_vector &tokens)
Referenced by parse, xtd::network::http::cpptempl::TokenEnd::TokenEnd.
string xtd::network::http::cpptempl::parse(string templ_text, data_map &data)
References tokenize, parse_tree.
Referenced by xtd::network::http::cpptempl::TokenEnd::TokenEnd, xtd::network::http::Template::resolve.
data_ptr xtd::network::http::cpptempl::make_data(string p_val)
Referenced by parse_val, xtd::network::http::cpptempl::TokenFor::gettext, make_data, xtd::network::http::Template::val.
data_ptr xtd::network::http::cpptempl::make_data(data_list &p_val)
data_ptr xtd::network::http::cpptempl::make_data(data_map &p_val)
data_ptr xtd::network::http::cpptempl::make_data(T &p_val)
References make_data.
data_ptr xtd::network::http::cpptempl::make_data(vector< T > &p_val)
References make_data.
data_ptr xtd::network::http::cpptempl::make_data(map< string, T > &p_val)
References make_data, parse_val.