xtd::ConfParser::const_iterator
typedef std::pair<const char*, const char*> xtd::ConfParser::const_iterator::t_result
t_section_list::const_iterator xtd::ConfParser::const_iterator::m_iter
xtd::ConfParser::const_iterator::const_iterator(void)
Referenced by xtd::ConfParser::begin, xtd::ConfParser::end.
xtd::ConfParser::const_iterator::const_iterator(const const_iterator &p_obj)
xtd::ConfParser::const_iterator::const_iterator(const t_section_list::const_iterator &p_iter)
ConfParser::const_iterator & xtd::ConfParser::const_iterator::operator=(const const_iterator &p_obj)
void xtd::ConfParser::const_iterator::operator++(void)
void xtd::ConfParser::const_iterator::operator++(int)
bool xtd::ConfParser::const_iterator::operator==(const const_iterator &p_obj) const
Referenced by operator!=.
bool xtd::ConfParser::const_iterator::operator!=(const const_iterator &p_obj) const
References operator==.
const ConfParser::const_iterator::t_result xtd::ConfParser::const_iterator::operator*(void) const