xtd::counters::Freq
friend class Composed
boost::posix_time::ptime xtd::counters::Freq::m_beginTime
uint32_t xtd::counters::Freq::m_nbEvent
xtd::counters::Freq::Freq(const string &p_name)
virtual xtd::counters::Freq::~Freq(void)
References tick, operator=, update_safe.
void xtd::counters::Freq::tick(void)
Referenced by xtd::counters::AvgTimedValue::addResponseTime, xtd::counters::Cache::hit, xtd::counters::Cache::miss, ~Freq, xtd::counters::Perf::stopChrono.
Freq & xtd::counters::Freq::operator=(const uint32_t &p_value)
References xtd::counters::Value< TType >::operator=.
Referenced by ~Freq.
void xtd::counters::Freq::update_safe(void)
References xtd::counters::Value< uint32_t >::m_value.
Referenced by ~Freq.