xtd::counters::InstantFreq
typedef std::deque<boost::posix_time::ptime> xtd::counters::InstantFreq::t_timevect
friend class Composed
t_timevect xtd::counters::InstantFreq::m_samples
const uint32_t xtd::counters::InstantFreq::m_timeDeltaMs
xtd::counters::InstantFreq::InstantFreq(const string &p_name, uint32_t p_timeDeltaMs=1000)
virtual xtd::counters::InstantFreq::~InstantFreq(void)
References tick, operator=, update_safe.
void xtd::counters::InstantFreq::tick(void)
References xtd::counters::Base::m_mutex.
Referenced by xtd::counters::AvgTimedValue::addResponseTime, xtd::counters::Cache::hit, xtd::counters::Cache::miss, ~InstantFreq, xtd::counters::Perf::stopChrono.
InstantFreq & xtd::counters::InstantFreq::operator=(uint32_t p_value)
References xtd::counters::Value< TType >::operator=.
Referenced by ~InstantFreq.
void xtd::counters::InstantFreq::update_safe(void)
References xtd::counters::Value< uint32_t >::m_value.
Referenced by ~InstantFreq.
bool xtd::counters::InstantFreq::expired_safe(const boost::posix_time::ptime &p_item, const boost::posix_time::ptime &p_now) const
void xtd::counters::InstantFreq::shrink_safe(const boost::posix_time::ptime &p_now)