xtd::counters::AvgValue
typedef boost::shared_ptr<AvgValue<TType> > xtd::counters::AvgValue< TType >::t_sptr
typedef std::deque<TType> xtd::counters::AvgValue< TType >::t_samples
friend class Composed
const uint32_t xtd::counters::AvgValue< TType >::mcs_defaultSampleSize
t_samples xtd::counters::AvgValue< TType >::m_samples
Value<TType> xtd::counters::AvgValue< TType >::m_mean
Value<TType> xtd::counters::AvgValue< TType >::m_min
Value<TType> xtd::counters::AvgValue< TType >::m_max
uint32_t xtd::counters::AvgValue< TType >::m_nbEvent
const uint32_t xtd::counters::AvgValue< TType >::m_sampleSize
xtd::counters::AvgValue< TType >::AvgValue(const string &p_name, uint32_t p_sampeSize=mcs_defaultSampleSize)
virtual xtd::counters::AvgValue< TType >::~AvgValue(void)
AvgValue& xtd::counters::AvgValue< TType >::operator=(const TType &p_value)
Referenced by xtd::counters::AvgValue< uint32_t >::~AvgValue.
AvgValue& xtd::counters::AvgValue< TType >::operator+(const AvgValue &p_value)
Referenced by xtd::counters::AvgValue< uint32_t >::~AvgValue.
void xtd::counters::AvgValue< TType >::affect_safe(const TType &p_value)
Referenced by xtd::counters::AvgValue< uint32_t >::~AvgValue.
void xtd::counters::AvgValue< TType >::add_safe(const AvgValue &p_value)
Referenced by xtd::counters::AvgValue< uint32_t >::~AvgValue.